;;; coal-graal-theme.el --- an Emacs 24 theme based on Coal Graal (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1406105789
;;; Original author: 
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Coal Graal (tmTheme) by 
;;
;;; Code:

(deftheme coal-graal
  "coal-graal-theme - Created by tmtheme-to-deftheme - 2014-07-23 10:56:29 +0200")

(custom-theme-set-variables
 'coal-graal
)

(custom-theme-set-faces
 'coal-graal
 ;; basic theming.

 '(default ((t (:foreground "#D8D9D1" :background "#222222" ))))
 '(region  ((t (:background "#6405D0"))))
 '(cursor  ((t (:background "#D8D9D1"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#464745"  :background "#343433" ))))
 '(fringe                              ((t (                       :background "#343433" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                        :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))

 '(mode-line-inactive                  ((t (:foreground "#b0b2a2"  :background "#343433" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#d8d9d1"  :background "#343433" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#B4DF61"  ))))
 '(font-lock-string-face ((t (:foreground "#ACC6D7"  ))))
 '(font-lock-builtin-face ((t (:foreground "#EDB272"  ))))
 '(font-lock-function-name-face ((t (:foreground "#DFCC94"  ))))
 '(js3-external-variable-face ((t (:foreground "#BBDFDD"  ))))
 '(js2-external-variable ((t (:foreground "#BBDFDD"  ))))
 '(js3-function-param-face ((t (:foreground "#85C6D9"  ))))
 '(js2-function-param ((t (:foreground "#85C6D9"  ))))
 '(font-lock-keyword-face ((t (:foreground "#A3AAD8"  ))))
 '(font-lock-type-face ((t (:foreground "#B998DF"  ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#B4DF61"  ))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#826b9d"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#8f7ba7"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#9d8bb2"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#aa9bbc"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#b8abc7"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#c5bbd1"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#d2cadc"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#e0dae7"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#edeaf1"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'coal-graal)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; coal-graal-theme.el ends here
