;;; sources-common.el ---

;; Copyright (C) 2011 Alex Ermolov
;;
;; Author: aaermolov@gmail.com
;; Keywords:
;; Requirements:
;; Status: not intended to be distributed yet

(setq el-get-packages
      '(
        ac-nrepl
        ac-php-doc
        ac-slime
        ace-jump-mode
        ag-custom
        auto-complete-emacs-lisp
        auto-complete-extension
        auto-complete-latex
        auto-complete-nxml
        auto-complete-rst
        auto-complete-yasnippet
        autosmiley
        bm
        bookmark+
        breadcrumb
        browse-kill-ring
        buff-menu+
        buffer-move
        c-eldoc
        calfw
        clojure-mode
        col-highlight
        color-theme
        column-marker
        crontab-mode
        crosshairs
        css-eldoc
        csv-mode
        cursor-chg
        deferred
        diminish
        dired+
        dired-details
        dired-details+
        dired-sort-menu
        direx
        django-mode
        dope
        doxymacs
        drag-stuff
        ecb-custom
        egit
        elwm
        emacs-w3m
        emacs-wgrep
        epoch-view
        erc-extras
        erc-highlight-nicknames
        eredis
        erefactor
        evil-nerd-commenter
        evil-surround
        expand-region
        f
        fic-mode
        flx
        flycheck
        flycheck-color-mode-line
        flymake-cursor
        git-commit-mode
        git-emacs
        git-gutter
        gitsum
        go-autocomplete-custom
        go-mode
        google-contacts
        haskellmode-emacs
        header2
        highlight-symbol
        hl-line+
        hs-lint
        ido-hacks
        ido-preview
        ido-ubiquitous
        ido-vertical-mode
        ido-yes-or-no
        iedit
        ioccur
        jedi-custom
        joseph-file-util
        js2-highlight-vars
        js2-mode
        js2-refactor
        json-mode
        jump-char
        lisppaste
        list-processes+
        litable-custom
        magit
        magit-filenotify
        magit-identities
        magit-tramp
        markdown-mode
        minibuf-electric-gnuemacs
        minimap
        mo-git-blame
        monky
        multiple-cursors
        nav
        nginx-mode
        notify
        nrepl
        nrepl-ritz
        nxhtml
        oauth2
        org-mode
        org-occur-goto
        pdftools-custom
        php-electric-custom
        php-mode-improved
        po-mode
        point-stack
        popwin
        projectile-custom
        python24
        pylookup
        python-pep8
        qmake-mode
        rainbow-delimiters
        rainbow-mode
        rebox2
        recentf-ext
        regex-tool
        region-bindings-mode
        replace+
        revive
        ropemacs
        rst-mode
        s
        sauron
        savekill
        scratch
        session
        silentcomp
        slime
        smart-forward
        smartparens
        smex
        sml-mode
        sunrise-commander
        tail
        twittering-mode
        undo-tree
        vline
        volatile-highlights
        w3m-session
        w3m-type-ahead
        wc-mode
        wdired
        whole-line-or-region
        window-number
        xgtags
        yandex-weather
        yasnippet
        zenburn-custom
        zencoding-mode
        ))

;;; sources-common.el ends here
