;;; sources-common.el ---

;; Copyright (C) 2011 Alex Ermolov
;;
;; Author: aaermolov@gmail.com
;; Keywords:
;; Requirements:
;; Status: not intended to be distributed yet

(setq el-get-packages
      '(
        ac-math
        ac-slime
        ace-jump-mode
        ag-custom
        auctex
        auto-complete-emacs-lisp
        auto-complete-extension
        auto-complete-latex
        auto-complete-nxml
        auto-complete-rst
        auto-complete-yasnippet
        bookmark+
        breadcrumb
        browse-kill-ring
        buffer-move
        c-eldoc
        calfw
        col-highlight
        column-marker
        crontab-mode
        crosshairs
        css-eldoc
        csv-mode
        cursor-chg
        deferred
        diminish
        dired+
        dired-sort-menu
        dope
        doxymacs
        drag-stuff
        ecb-custom
        elwm
        emacs-w3m
        emacs-wgrep
        emmet-mode
        epoch-view
        erc-extras
        erc-highlight-nicknames
        erefactor
        evil-nerd-commenter
        evil-surround
        expand-region
        f
        fic-mode
        flx
        flycheck
        flycheck-color-mode-line
        framemove
        git-commit-mode
        git-emacs
        git-gutter
        go-autocomplete-custom
        go-mode
        google-contacts
        haskellmode-emacs
        header2
        helm-swoop
        highlight-symbol
        hl-line+
        hs-lint
        ido-hacks
        ido-preview
        ido-ubiquitous
        ido-vertical-mode
        ido-yes-or-no
        init-paredit
        jedi-custom
        joseph-file-util
        js2-highlight-vars
        js2-mode
        js2-refactor
        json-mode
        lisppaste
        list-processes+
        litable-custom
        magit
        markdown-mode
        minibuf-electric-gnuemacs
        minimap
        multiple-cursors
        nav
        nginx-mode
        notify
        nxhtml
        oauth2
        org-mode
        org-magit
        org-occur-goto
        paredit
        pdftools-custom
        po-mode
        popwin
        prodigy
        projectile
        python24
        pylookup
        python-pep8
        qmake-mode
        rainbow-delimiters
        rainbow-mode
        rebox2
        recentf-ext
        regex-tool
        region-bindings-mode
        replace+
        restclient-custom
        ropemacs
        rst-mode
        s
        sauron
        savekill
        scratch
        silentcomp
        slime
        smex
        sml-mode
        swank-js
        tail
        twittering-mode
        undo-tree
        vline
        volatile-highlights
        w3m-session
        w3m-type-ahead
        wc-mode
        wdired
        whole-line-or-region
        window-number
        wrap-region
        yandex-weather
        yasnippet
        zenburn-custom
        ))

(provide 'packages-lean)

;;; sources-common.el ends here
