;;; sources-common.el ---

;; Copyright (C) 2011 Alex Ermolov
;;
;; Author: aaermolov@gmail.com
;; Keywords:
;; Requirements:
;; Status: not intended to be distributed yet

(setq el-get-packages
      '(
        ac-math
        ac-slime
        ac-irony
        ace-link
        ace-window
        actionscript-mode
        adaptive-wrap
        ag-custom
        anchored-transpose
        auctex
        auto-complete-c-headers
        auto-complete-clang
        auto-complete-emacs-lisp
        auto-complete-extension
        auto-complete-latex
        auto-complete-yasnippet
        base16
        bbdb
        bitlbee
        bookmark+
        breadcrumb-custom
        c-eldoc
        calfw
        col-highlight
        color-theme-zenburn
        column-marker
        crontab-mode
        crosshairs
        css-eldoc
        csv-mode-custom
        cursor-chg
        deft
        diminish
        discover
        dired+
        dired-sort-menu
        dired-toggle-sudo
        doxymacs
        drag-stuff
        dtrt-indent
        ecb-custom
        el-spice
        elisp-slime-nav
        emacs-jabber
        emacs-swoop
        emacs-w3m
        wgrep
        emmet-mode
        epoch-view
        erc-extras
        erc-highlight-nicknames
        erefactor
        expand-region
        fic-mode
        file-template
        flx
        flycheck
        flycheck-color-mode-line
        framemove
        ggtags
        git-commit-mode
        git-emacs
        git-gutter
        git-timemachine
        gmail-notifier
        google-contacts
        google-translate
        haskell-mode
        helm-gtags
        helm-recentd
        help+
        hide-comnt
        hl-line+
        hs-lint
        hungry-delete-el
        hydra
        ido-hacks
        ido-preview
        ido-ubiquitous
        ido-vertical-mode-custom
        ido-yes-or-no
        init-paredit
        irony-mode
        jedi
        joseph-file-util
        js2-highlight-vars
        js2-mode
        js2-refactor
        json-mode
        keyfreq
        latex-preview-pane
        list-processes+
        lua-mode
        magit
        magit-filenotify
        markdown-mode
        mingus
        minibuf-electric-gnuemacs
        minimap
        multifiles
        multiple-cursors
        neotree
        nginx-mode
        notify
        nxhtml
        oauth2
        openwith
        org-magit
        org-occur-goto
        org-pomodoro
        org-toodledo
        paredit
        paredit-everywhere
        pdftools
        po-mode
        popwin
        projectile
        python24
        pylookup
        python-pep8
        rainbow-mode
        rebox2
        recentf-ext
        regex-tool
        region-bindings-mode
        replace+
        restclient
        revbufs
        rst-mode
        rtags
        sauron
        savekill
        scratch
        slime
        smart-forward
        smex
        swank-js
        tail
        tern
        twittering-mode
        undo-tree
        use-package
        vimrc-mode
        vline
        volatile-highlights
        w3m-session
        w3m-type-ahead
        wc-mode
        wdired
        whole-line-or-region
        window-number
        wrap-region
        yandex-weather
        yasnippet
        zen-and-art-theme
        zoom-window
        ))

(provide 'packages)

;;; sources-common.el ends here
