;;; sources-common.el ---

;; Copyright (C) 2011 Alex Ermolov
;;
;; Author: aaermolov@gmail.com
;; Keywords:
;; Requirements:
;; Status: not intended to be distributed yet

(setq el-get-packages
      '(
        ac-math
        ac-slime
        ac-irony
        ace-jump-mode
        actionscript-mode
        ag-custom
        ample-theme
        auctex
        auto-complete-c-headers
        auto-complete-clang
        auto-complete-emacs-lisp
        auto-complete-extension
        auto-complete-latex
        auto-complete-nxml
        auto-complete-rst
        auto-complete-yasnippet
        bm
        bookmark+
        breadcrumb-custom
        browse-kill-ring
        buffer-move
        c-eldoc
        calfw
        cedet
        col-highlight
        color-theme-zenburn
        column-marker
        crontab-mode
        crosshairs
        css-eldoc
        csv-mode-custom
        cursor-chg
        deferred
        deft
        diminish
        discover
        dired+
        dired-sort-menu
        dired-toggle-sudo
        doxymacs
        drag-stuff
        dtrt-indent
        ecb-custom
        el-spice
        elisp-slime-nav
        elwm
        emacs-jabber
        emacs-swoop
        emacs-w3m
        wgrep
        emmet-mode
        epoch-view
        erc-extras
        erc-highlight-nicknames
        erefactor
        evil-nerd-commenter
        evil-surround
        expand-region
        f
        fic-mode
        flx
        flycheck
        flycheck-color-mode-line
        framemove
        ggtags
        git-commit-mode
        git-emacs
        git-gutter
        gmail-notifier
        go-autocomplete-custom
        go-mode
        google-contacts
        google-translate
        haskell-mode
        header2
        helm-gtags
        helm-recentd
        help+
        highlight-symbol
        hl-line+
        hs-lint
        hungry-delete-el
        ido-hacks
        ido-preview
        ido-ubiquitous
        ido-vertical-mode
        ido-yes-or-no
        init-paredit
        irony-mode
        jedi
        joseph-file-util
        js2-highlight-vars
        js2-mode
        js2-refactor
        json-mode
        latex-preview-pane
        lisppaste
        list-processes+
        litable
        lua-mode
        magit
        magit-filenotify
        markdown-mode
        mingus
        minibuf-electric-gnuemacs
        minimap
        multifiles
        multiple-cursors
        neotree
        nginx-mode
        notify
        nxhtml
        oauth2
        openwith
        org-mode
        org-magit
        org-occur-goto
        org-pomodoro
        org-trello
        org-toodledo
        paredit
        paredit-everywhere
        pdftools
        po-mode
        popwin
        prodigy
        projectile
        python24
        pylookup
        python-pep8
        qmake-mode
        rainbow-mode
        rebox2
        recentf-ext
        regex-tool
        region-bindings-mode
        replace+
        restclient
        revbufs
        ropemacs
        rst-mode
        rtags
        s
        sauron
        savekill
        scratch
        slime
        smex
        sml-mode
        swank-js
        tail
        tern
        twittering-mode
        undo-tree
        unicad
        use-package
        vimrc-mode
        vline
        volatile-highlights
        w3m-session
        w3m-type-ahead
        wc-mode
        wdired
        whole-line-or-region
        window-number
        wrap-region
        yandex-weather
        yasnippet
        zen-and-art-theme
        ))

(provide 'packages)

;;; sources-common.el ends here
