(add-to-list 'load-path (concat config-basedir "/ext/icicles"))
(load (concat config-basedir "/ext/zenburn.el"))
(load (concat config-basedir "/ext/window-number.el"))
(add-to-list 'load-path (concat config-basedir "/ext/git-contrib/emacs"))
(add-to-list 'load-path (concat config-basedir "/ext/crosshairs"))
(add-to-list 'load-path (concat config-basedir "/ext/bookmark+"))
(add-to-list 'load-path (concat config-basedir "/ext/php"))
(load (concat config-basedir "/ext/php/php-mode/php-mode.el"))
(load (concat config-basedir "/ext/php/php-electric.el"))
(load (concat config-basedir "/ext/python/python-pep8.el"))
(load (concat config-basedir "/ext/python/python-pylint.el"))
(add-to-list 'load-path (concat config-basedir "/ext/emacs-jabber"))
;(add-to-list 'load-path (concat config-basedir "/ext/python/pymacs"))
(load (concat config-basedir "/ext/minimap.el"))
(load (concat config-basedir "/ext/pretty-mode.el"))