(add-to-list 'load-path (concat config-basedir "/ext/ace-jump-mode"))
(add-to-list 'load-path (concat config-basedir "/ext/bookmark+"))
(add-to-list 'load-path (concat config-basedir "/ext/crosshairs"))
(add-to-list 'load-path (concat config-basedir "/ext/ecb"))
(add-to-list 'load-path (concat config-basedir "/ext/emacs-jabber"))
(add-to-list 'load-path (concat config-basedir "/ext/emacs-nav"))
(add-to-list 'load-path (concat config-basedir "/ext/git-contrib/emacs"))
(add-to-list 'load-path (concat config-basedir "/ext/helm"))
(add-to-list 'load-path (concat config-basedir "/ext/icicles"))
(add-to-list 'load-path (concat config-basedir "/ext/php"))
(add-to-list 'load-path (concat config-basedir "/ext/projectile"))
(add-to-list 'load-path (concat config-basedir "/ext/sauron"))
(add-to-list 'load-path (concat config-basedir "/ext/slime"))
(add-to-list 'load-path (concat config-basedir "/ext/slime/contrib"))
(add-to-list 'load-path (concat config-basedir "/ext/twittering-mode"))
(add-to-list 'load-path (concat config-basedir "/ext/workgroups.el"))
(add-to-list 'load-path (concat config-basedir "/ext/zencoding"))
(add-to-list 'load-path (concat config-basedir "/ext/ghc-mod"))

(load (concat config-basedir "/ext/auto-complete.el"))
(load (concat config-basedir "/ext/anything-grep.el"))
(load (concat config-basedir "/ext/browse-kill-ring.el"))
(load (concat config-basedir "/ext/buff-menu+.el"))
(load (concat config-basedir "/ext/buffer-move.el"))
(load (concat config-basedir "/ext/camelCase-mode.el"))
(load (concat config-basedir "/ext/change-windows-intuitively.el"))
(load (concat config-basedir "/ext/color-theme-solarized.el"))
(load (concat config-basedir "/ext/column-marker.el"))
(load (concat config-basedir "/ext/command-log-mode/command-log-mode.el"))
(load (concat config-basedir "/ext/csv-mode.el"))
(load (concat config-basedir "/ext/fastnav.el/fastnav.el"))
(load (concat config-basedir "/ext/fill-column-indicator.el"))
(load (concat config-basedir "/ext/helm-slime/helm-slime.el"))
(load (concat config-basedir "/ext/hexview-mode.el"))
(load (concat config-basedir "/ext/himark.el"))
(load (concat config-basedir "/ext/minimap.el"))
(load (concat config-basedir "/ext/org-occur-goto.el"))
(load (concat config-basedir "/ext/paredit.el"))
(load (concat config-basedir "/ext/parenface.el"))
(load (concat config-basedir "/ext/pdftools.el"))
(load (concat config-basedir "/ext/php/php-mode/php-mode.el"))
(load (concat config-basedir "/ext/php/php-electric.el")) ;; AFTER php-mode !!!
(load (concat config-basedir "/ext/point-stack/point-stack.el"))
(load (concat config-basedir "/ext/python/python-pep8.el"))
(load (concat config-basedir "/ext/python/python-pylint.el"))
(load (concat config-basedir "/ext/quick-jump.el"))
(load (concat config-basedir "/ext/rainbow-mode.el"))
(load (concat config-basedir "/ext/rebox2/rebox2.el"))
(load (concat config-basedir "/ext/rst.el"))
(load (concat config-basedir "/ext/savekill.el"))
(load (concat config-basedir "/ext/silentcomp.el"))
(load (concat config-basedir "/ext/smerge-mode.el"))
(load (concat config-basedir "/ext/twilight-emacs/color-theme-twilight.el"))
(load (concat config-basedir "/ext/unbound.el"))
(load (concat config-basedir "/ext/webjump-plus.el"))
(load (concat config-basedir "/ext/window-number.el"))
(load (concat config-basedir "/ext/workspaces.el"))
(load (concat config-basedir "/ext/zenburn-el/zenburn.el"))
(load (concat config-basedir "/ext/erefactor.el"))
(load (concat config-basedir "/ext/minibuf-electric-gnuemacs.el"))
(load (concat config-basedir "/ext/devel-notes.el"))
(load (concat config-basedir "/ext/electric-dot-and-dash.el"))
(load (concat config-basedir "/ext/header2.el"))
(load (concat config-basedir "/ext/flymake-cursor.el"))
(load (concat config-basedir "/ext/framemove.el"))

;; (add-to-list 'load-path (concat config-basedir "/ext/frame-tag.el"))
;; (add-to-list 'load-path (concat config-basedir "/ext/python/pymacs"))
;; (load (concat config-basedir "/ext/dired+.el"))
;; (load (concat config-basedir "/ext/joseph-go-to-char.el"))
;; (load (concat config-basedir "/ext/multi-term.el"))
;; (load (concat config-basedir "/ext/naquadah-theme/naquadah-theme.el"))
;; (load (concat config-basedir "/ext/nxhtml/autostart.el"))
;; (load (concat config-basedir "/ext/pretty-mode.el"))
