(add-to-list 'load-path (concat config-basedir "/ext/ace-jump-mode"))
(add-to-list 'load-path (concat config-basedir "/ext/bookmark+"))
(add-to-list 'load-path (concat config-basedir "/ext/crosshairs"))
(add-to-list 'load-path (concat config-basedir "/ext/ecb"))
(add-to-list 'load-path (concat config-basedir "/ext/emacs-jabber"))
(add-to-list 'load-path (concat config-basedir "/ext/git-contrib/emacs"))
(add-to-list 'load-path (concat config-basedir "/ext/helm"))
(add-to-list 'load-path (concat config-basedir "/ext/icicles"))
(add-to-list 'load-path (concat config-basedir "/ext/php"))
(add-to-list 'load-path (concat config-basedir "/ext/projectile"))
(add-to-list 'load-path (concat config-basedir "/ext/twittering-mode"))
(add-to-list 'load-path (concat config-basedir "/ext/zencoding"))

(load (concat config-basedir "/ext/buff-menu+.el"))
(load (concat config-basedir "/ext/camelCase-mode.el"))
(load (concat config-basedir "/ext/color-theme-solarized.el"))
(load (concat config-basedir "/ext/command-log-mode/command-log-mode.el"))
(load (concat config-basedir "/ext/kill-ring-search.el"))
(load (concat config-basedir "/ext/minimap.el"))
(load (concat config-basedir "/ext/pdftools.el"))
(load (concat config-basedir "/ext/php/php-mode/php-mode.el"))
(load (concat config-basedir "/ext/php/php-electric.el")) ;; AFTER php-mode !!!
(load (concat config-basedir "/ext/point-stack/point-stack.el"))
(load (concat config-basedir "/ext/python/python-pep8.el"))
(load (concat config-basedir "/ext/python/python-pylint.el"))
(load (concat config-basedir "/ext/rebox2/rebox2.el"))
(load (concat config-basedir "/ext/silentcomp.el"))
(load (concat config-basedir "/ext/smerge-mode.el"))
(load (concat config-basedir "/ext/window-number.el"))
(load (concat config-basedir "/ext/workspaces.el"))
(load (concat config-basedir "/ext/zenburn-el/zenburn.el"))

;; (add-to-list 'load-path (concat config-basedir "/ext/frame-tag.el"))
;; (add-to-list 'load-path (concat config-basedir "/ext/python/pymacs"))
;; (load (concat config-basedir "/ext/joseph-go-to-char.el"))
;; (load (concat config-basedir "/ext/pretty-mode.el"))
