;;; sources-common.el ---

;; Copyright (C) 2011 Alex Ermolov
;;
;; Author: aaermolov@gmail.com
;; Keywords:
;; Requirements:
;; Status: not intended to be distributed yet

(setq el-get-packages
      '(
        ac-nrepl
        ac-php-doc
        ac-slime
        ace-jump-mode
        ag-custom
        ahg
        auto-complete-rst
        auto-complete-emacs-lisp
        auto-complete-extension
        auto-complete-latex
        auto-complete-nxml
        auto-complete-yasnippet
        autosmiley
        bookmark+
        breadcrumb
        browse-kill-ring
        buff-menu+
        buffer-move
        c-eldoc
        calfw
        clojure-mode
        col-highlight
        color-theme
        column-marker
        crosshairs
        csv-mode
        cursor-chg
        deferred
        diminish
        dired+
        dired-details
        dired-sort-menu
        django-mode
        dope
        doxymacs
        drag-stuff
        ecb-custom
        egit
        elwm
        emacs-w3m
        emacs-wgrep
        epoch-view
        erc-highlight-nicknames
        erefactor
        evil-nerd-commenter
        evil-surround
        f
        flycheck
        flycheck-color-mode-line
        flymake-cursor
        ggtags
        git-emacs
        gitsum
        go-mode
        google-contacts
        haskellmode-emacs
        header2
        highlight-symbol
        hl-line+
        hs-lint
        ido-preview
        ido-ubiquitous
        iedit
        ioccur
        iy-go-to-char
        jedi-custom
        joseph-file-util
        js2-highlight-vars
        js2-mode
        json-mode
        key-chord
        markdown-mode
        minibuf-electric-gnuemacs
        mo-git-blame
        multiple-cursors
        nav
        nrepl
        nxhtml
        oauth2
        org-mode
        org-occur-goto
        pdftools-custom
        po-mode
        point-stack
        pony-mode
        popwin
        pylookup
        python
        python-pep8
        rainbow-delimiters
        rainbow-mode
        rebox2
        regex-tool
        region-bindings-mode
        replace+
        revive
        ropemacs
        rst-mode
        s
        sauron
        savekill
        silentcomp
        slime
        smartparens
        smex
        sml-mode
        sr-speedbar
        sunrise-commander
        tail
        twittering-mode
        undo-tree
        vline
        volatile-highlights
        wc-mode
        wdired
        web-mode
        whole-line-or-region
        window-number
        xgtags
        yandex-weather
        yasnippet
        zenburn-theme
        zencoding-mode
        ))

;;; sources-common.el ends here
