;;; sources-common.el ---

;; Copyright (C) 2011 Alex Ermolov
;;
;; Author: aaermolov@gmail.com
;; Keywords:
;; Requirements:
;; Status: not intended to be distributed yet

(setq el-get-packages
      '(
        ac-nrepl-custom
        ac-php-doc-custom
        ac-slime
        ace-jump-mode
        ag-custom
        ahg
        auto-complete-rst
        autosmiley
        bookmark+
        breadcrumb
        browse-kill-ring
        buff-menu+
        buffer-move
        c-eldoc
        calfw
        cl-lib-custom
        clojure-mode
        col-highlight
        color-theme
        column-marker
        crosshairs
        csv-mode-custom
        cursor-chg
        dash-custom
        deferred
        diminish
        dired+
        dired-details
        dired-sort-menu
        django-mode
        dope-custom
        doxymacs
        drag-stuff
        ecb
        egit-custom
        elwm-custom
        emacs-ctable-custom
        emacs-epc-custom
        emacs-helm-gtags-custom
        emacs-jedi-custom
        emacs-w3m
        epoch-view-custom
        erc-highlight-nicknames
        erefactor
        evil-nerd-commenter-custom
        evil-surround
        f-custom
        flycheck-color-mode-line-custom
        flycheck-custom
        flymake-cursor
        ggtags-custom
        git-emacs
        gitsum-custom
        go-mode
        google-contacts
        haskellmode-emacs
        header2
        helm
        highlight-symbol
        hl-line+
        hs-lint
        ido-preview
        ido-ubiquitous
        iedit
        ioccur
        iy-go-to-char
        joseph-file-util
        js2-highlight-vars-custom
        json-mode-custom
        key-chord
        markdown-mode
        minibuf-electric-gnuemacs
        mo-git-blame
        mooz-js2-mode-custom
        multiple-cursors
        nav
        nrepl-custom
        nxhtml
        oauth2
        org-mode
        org-occur-goto-custom
        pdftools-custom
        pkg-info-custom
        po-mode
        point-stack
        pony-mode
        popwin
        pylookup-custom
        python-pep8
        rainbow-delimiters
        rainbow-mode
        rebox2
        regex-tool
        region-bindings-mode-custom
        replace+
        revive
        ropemacs
        rst-mode
        s-custom
        sauron
        savekill
        silentcomp-custom
        slime
        smartparens-custom
        smex
        sml-mode
        sr-speedbar
        sunrise-commander
        tail
        twittering-mode
        undo-tree
        vline
        volatile-highlights
        wc-mode
        wdired
        web-mode-custom
        whole-line-or-region
        window-number
        xgtags
        yandex-weather-custom
        yasnippet
        zenburn-theme
        zencoding-mode
        ))

;;; sources-common.el ends here
