;;; macosx-common.el ---

;; Copyright (C) 2011 Alex Ermolov
;;
;; Author: aaermolov@gmail.com
;; Keywords:
;; Requirements:
;; Status: not intended to be distributed yet

(require 'rc-abbrevs)
(require 'rc-recentf)
(require 'rc-yasnippet)
(require 'rc-bookmarks)
(require 'rc-ido)
(require 'rc-helm)
(require 'rc-smex)
(require 'rc-deft)
(require 'rc-enable)
(require 'rc-interface)
(require 'rc-system)
(require 'rc-server)
(require 'rc-themes)
(require 'rc-backups)
(require 'rc-editing)
(require 'rc-auto-complete)
(require 'rc-header2)
(require 'rc-rebox2)
(require 'rc-region-bindings)
(require 'rc-wrap-region)
(require 'rc-paredit)
(require 'rc-drag-stuff)
(require 'rc-multiple-cursors)
(require 'rc-rainbow-delimiters)
(require 'rc-zencoding)
(require 'rc-erc)
(require 'rc-jabber)
(require 'rc-jabber-faces)
(require 'rc-twitter)
(require 'rc-pomodoro)
(require 'rc-shell)
(require 'rc-tramp)
(require 'rc-sh-mode)
(require 'rc-browse-kill-ring)
(require 'rc-search)
(require 'rc-minimap)
(require 'rc-wincontrol)
(require 'rc-calfw)
(require 'rc-org-capture)
(require 'rc-org-mode)
(require 'rc-common-hooks)
(require 'rc-prog-common)
(require 'rc-evil)
(require 'rc-markup)
(require 'rc-elisp)
(require 'rc-javascript)
(require 'rc-lisp)
(require 'rc-haskell)
(require 'rc-python)
(require 'rc-golang)
(require 'rc-expand-region)
(require 'rc-pylookup)
(require 'rc-prodigy)
(require 'rc-doxygen)
(require 'rc-ecb)
(require 'rc-flycheck)
(require 'rc-gdb)
(require 'rc-smerge-mode)
(require 'rc-projectile)
(require 'rc-tex)
(require 'rc-gmail)
(require 'rc-mingus)
(require 'rc-git)
(require 'rc-dired)
(require 'rc-info)
(require 'rc-diminish)
(require 'rc-edit-portage)

(provide 'bundle-main)
;;; macosx-common.el ends here
