;;; macosx-common.el ---

;; Copyright (C) 2011 Alex Ermolov
;;
;; Author: aaermolov@gmail.com
;; Keywords:
;; Requirements:
;; Status: not intended to be distributed yet

(require 'rc-abbrevs)
;; (require 'rc-dir-locals)
(require 'rc-recentf)
(require 'rc-yasnippet)
(require 'rc-bookmarks)
(require 'rc-ido)
(require 'rc-smex)
(require 'rc-enable)
(require 'rc-sauron)
(require 'rc-interface)
(require 'rc-system)
(require 'rc-server)
(require 'rc-themes)
(require 'rc-backups)
(require 'rc-editing)
(require 'rc-evil)
(require 'rc-auto-complete)
(require 'rc-header2)
(require 'rc-rebox2)
(require 'rc-region-bindings)
(require 'rc-smartparens)
(require 'rc-drag-stuff)
(require 'rc-multiple-cursors)
(require 'rc-rainbow-delimiters)
(require 'rc-zencoding)
(require 'rc-erc)
(require 'rc-jabber)
(require 'rc-jabber-faces)
(require 'rc-twitter)
(require 'rc-shell)
(require 'rc-tramp)
(require 'rc-sh-mode)
(require 'rc-browse-kill-ring)
(require 'rc-search)
(require 'rc-tail)
(require 'rc-wincontrol)
(require 'rc-calfw)
(require 'rc-org-capture)
(require 'rc-org-mode)
(require 'rc-common-hooks)
(require 'rc-prog-common)
(require 'rc-tiny)
;; (require 'rc-generic)
;; (require 'rc-cedet)
(require 'rc-global)
(require 'rc-lang-markup)
(require 'rc-lang-elisp)
(require 'rc-lang-javascript)
(require 'rc-lang-lisp)
(require 'rc-lang-haskell)
(require 'rc-lang-perl)
(require 'rc-lang-php)
(require 'rc-lang-python)
(require 'rc-lang-go)
(require 'rc-pylookup)
(require 'rc-tools-doxygen)
(require 'rc-tools-ecb)
(require 'rc-tools-flycheck)
(require 'rc-tools-gdb)
(require 'rc-tools-smerge-mode)
(require 'rc-vcs-hg)
(require 'rc-ps-print)
(require 'rc-pdftools)
(require 'rc-dired)
(require 'rc-info)
(require 'rc-diminish)
(require 'rc-edit-portage)
(require 'defun-recipes)

;;; macosx-common.el ends here
